# Generated by Django 5.2 on 2025-04-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secure', '0002_profile_reset_token_profile_reset_token_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reset_token_created_at',
            new_name='reset_code_created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='code_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
